version: '3.8'

services:
  mongo:
    image: mongo
    container_name: local-mongo
    ports:
      - 27017:27017
    volumes:
      - ~/dev/db/mongo:/data/db
    environment:
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=viva_innovation